// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Day21.DAL.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Department { get; set; }

    public decimal Salary { get; set; }

    public string ImageName { get; set; }

    public string ImagePath { get; set; }
}